---
- name: Install networking and virtualization tools on CentOS
  hosts: all
  become: true
  vars_files: 
    - vars.yml
  
  tasks:
    - name: Install yum-utils 
      yum:
        name: yum-utils
        state: present

    - name: Add repository
      shell: sudo yum-config-manager --add-repo "{{item.baseurl}}"
      loop: "{{repo}}"
    
    - name: installing yum based packages
      become: true 
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{yum_packages}}"
    
    - name: installing dnf packages 
      ansible.builtin.dnf:
        name: "{{item}}"
        state: present
      loop: "{{dnf_packages}}"

    - name: enable services
      systemd:
        name: "{{item}}"
        enabled: true
        state: started
      loop: "{{services}}"

    - name: enable cockpit firewall
      ansible.posix.firewalld:
        service: cockpit
        port: 9090/tcp
        permanent: true 
        state: enabled
  
    - name:  reload firewalld
      ansible.posix.firewalld:
        state: reloaded
    
   


      

        

 